import CartSync from "@/components/auth/CartSync";
import ReduxProvider from "@/redux/ReduxProvider";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          {/* 👇 Add PWA manifest + theme color */}
          <link rel="manifest" href="/manifest.json" />
          <meta name="theme-color" content="#ffffff" />

          {/* Optional: icons for PWA install prompt */}
          <link rel="icon" href="/icons/icon-192x192.png" type="image/png" />
          <link rel="apple-touch-icon" href="/icons/icon-512x512.png" />
        </head>

        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ReduxProvider>
            <CartSync />
            {children}
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
